kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: argocd-server-redirect
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: argocd.lab.madtech.cx
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 80
        path: /
        pathType: Prefix
