apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  annotations:
    "helm.sh/hook": post-install
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argocd/apps
    repoURL: https://github.com/madeddie/homelab
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
