apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg-cluster
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.4.3
  instances: 1

  postgresql:
    shared_preload_libraries:
      - vchord.so

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
