apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg-cluster
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.3.0
  instances: 1
  postgresql:
    shared_preload_libraries:
      - vchord.so
  storage:
    size: 1Gi
    storageClass: local-path
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
