traefik:
  ingressRoute:
    dashboard:
      enabled: true
  service:
    spec:
      loadBalancerIP: 192.168.0.240
  providers:
    kubernetesCRD:
      allowExternalNameServices: true
    kubernetesIngress:
      allowExternalNameServices: true
  certificatesResolvers:
    letsencrypt:
      acme:
        email: edwin@madtech.cx
        storage: /data/acme.json
        httpChallenge:
          entryPoint: web
  persistence:
    enabled: true
    storageClass: local-path
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
