traefik:
  ingressRoute:
    dashboard:
      enabled: true
  service:
    spec:
      loadBalancerIP: 192.168.0.240
  providers:
    kubernetesCRD:
      allowExternalNameServices: true
      allowCrossNamespace: true
    kubernetesIngress:
      allowExternalNameServices: true
  env:
    - name: HURRICANE_TOKENS
      valueFrom:
        secretKeyRef:
          name: he-token-secret
          key: hurricane_tokens
  certificatesResolvers:
    le-http:
      acme:
        email: edwin@madtech.cx
        storage: /data/acme-http.json
        httpChallenge:
          entryPoint: web
    le-dns:
      acme:
        email: edwin@madtech.cx
        storage: /data/acme-dns.json
        dnsChallenge:
          resolvers:
            - "1.1.1.1:53"
            - "8.8.8.8:53"
          provider: hurricane
  persistence:
    enabled: true
    storageClass: local-path
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
