apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mosquitto-users-secret
spec:
    secretTemplates:
        - name: mosquitto-users-secret
          stringData:
            passwords.conf: ENC[AES256_GCM,data:OhPDiWOL/TfuLiAuljybu79ihCT0EHLClcjrrPYS+QzDrFObAO+0Ev05kB1blYKs6xkkYtNflInoGexALnxiRAiz05B1wURHPdN6eQDLQiVmKRT+DA2suxY91rL0d4FDYHhDSTSv+Vj1oFcOnpljhsIK1Tec0jvyK90KeQKLmJCSV+DEPC/8W6/el3BpvvWuhtaLl5+mcU4dRaqGit/W6kOKffxktUeiEnVpIK/wOLXi6qzjPndmLb2fD9s4duDsAPo3xGv9jFjeds6G2GKyeghSkOFZ/hVnFF9+KVwCR5w5jcAlnWrDWbzkuH2SsmFMzkR+NgVXcBRmzhdKLwp+8Ut3EfmMD6qNy4GW0cbl34Hp9tJcbnaWcfIPZ+ScX5AcQu6tUYrGx8LlFKSTC6kvgOQDLTiZDnQlWoVtayacjy+137TDnGCNPtay7ad7+zQa8buyD7NoUFVIjYdlj1cuAg81OezhCctm90kIXOIbel+XWx+DYEVEcu/+xCvX9WvmKsCtl8HbczbH2pAUxP8k/jDZS4cR83S3lizg69OG1Wifv6MSqScUVicJRNDFpggmg+croDuakxUamjjB5fb15JPwPHBr4y2BTg/uEDxn18LFBHKH7DbpjoZxw18ojwNcfCLnQanMqFwQO6iv6owAMCA/T/9Z4LjBw3rMNjZ10a3O7sOrRO9JCf4lZnm7PO1SslG0DIcmNXV11/ZdPEn2ABACGMeTWFqX5uxh2Fk2Ye6PP5YEay2eiP7U4EEyTIb3hWHVDMrogpD9H7g16RqY1F373F5l2uV380fhJttvRMg+5x+2H59aFzdN,iv:qyczbT8j7nbY3o1F/PIvZuDOWqWB7JNsLRXBt7tF0Tk=,tag:3WH9JSXPbqGUoId43Iwcng==,type:str]
sops:
    age:
        - recipient: age13jkfzky97zmm4n738k3wy8leguhz6xy6xas9r4etnx2esyafadvqat4qve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWUZjbFNqcitlSnVjczEz
            dmZWem5LR2ZVQzB0V2xud2R4amhDKy9ncGd3CnRCYjdqRUFxZUVyeTE5OVFSUXZH
            N3ptWVlqWSs1RlpBMk5PcWt0bHprY1EKLS0tIGZ5WmlOam9UMVM3dForOGZyVm9H
            K1gxOCttWm1sWDRVREhreXEwby9XQkUK2uTZOKN1ZSokWNyT1CRO7+l0jxWPXmml
            Y22l2YWHc/tYI7cMF3FwnMoKnOqTpkW/oi8X5rhjnCFe7fkqUFkq3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T16:52:03Z"
    mac: ENC[AES256_GCM,data:Cy0XLdhvMHR6qZXem8d4ozsRgfFbFLzhBb28O+UJmx0PDtPeO1GEV6lLAI3QnlCxm+Drt6sR2PVI3SdAEWCYeQdFWL/+C4gYjRSLqMoot3y9m+pL52limBOD7qoLSAjrbVRBlFHZ0ExOjcSzEn1VLP/XLPWM4b0nBbix/icXQ6M=,iv:j9BYu1oTqroCnZbDP9Zt3qPijfmM+MUIXa6ibQ/UStU=,tag:yFWNnvMGrw0ZaOYjehBcfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
