keycloak:
  auth:
    adminUser: admin
    existingSecret: keycloak-secret
    passwordSecretKey: admin-password
  ingress:
    enabled: true
    hostname: keycloak.svc.madtech.cx
  proxy: edge
  production: true
