apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg-cluster
spec:
  instances: 1

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - authentik
        source:
          externalCluster: authentik-postgresql

  externalClusters:
    - name: authentik-postgresql
      connectionParameters:
        host: authentik-postgresql
        user: authentik
        dbname: postgres
      password:
        name: authentik-pg-cluster-app
        key: password
