clusterName: homelab
talosVersion: v1.10.1
kubernetesVersion: v1.32.3
endpoint: https://cluster.lab.madtech.cx:6443
allowSchedulingOnControlPlanes: true
nodes:
  - hostname: homelab1
    ipAddress: 192.168.0.115
    installDisk: /dev/sda
    controlPlane: true
  - hostname: homelab2
    ipAddress: 192.168.0.120
    installDisk: /dev/sda
    controlPlane: true
  - hostname: homelab3
    ipAddress: 192.168.0.125
    installDisk: /dev/sda
    controlPlane: true
controlPlane:
  networkInterfaces:
    - deviceSelector:
        physical: true
      dhcp: true
      vip:
        ip: 192.168.0.15
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
  machineFiles:
    - content: |
        [plugins]
          [plugins."io.containerd.grpc.v1.cri"]
            device_ownership_from_security_context = true
          [plugins."io.containerd.cri.v1.runtime"]
            device_ownership_from_security_context = true
      path: /etc/cri/conf.d/20-customization.part
      op: create
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraMounts
        value:
          - destination: /var/lib/longhorn
            type: bind
            source: /var/lib/longhorn
            options:
              - bind
              - rshared
              - rw
          - destination: /var/lib/local-path-provisioner
            type: bind
            source: /var/lib/local-path-provisioner
            options:
              - bind
              - rshared
              - rw
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          rotate-server-certificates: true
