apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: keycloak-secret
    namespace: keycloak
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:7s4qz7rmDNJ9u1DiQefi,iv:ueCCeDXlRJjDGr6v9lymSDHcebGXKd8Po/SqvQqVs14=,tag:bjTiDUEOAYh77t01NbAwJQ==,type:str]
          stringData:
            admin-password: ENC[AES256_GCM,data:Vuwj+DwVZLLR,iv:md60S+1SWpXPO3IMefF7XBoR4fQWAe8HsfMqpXnOr6Y=,tag:Bk2aHs5NeDka11QtpLKUZA==,type:str]
            postgres-password: ENC[AES256_GCM,data:2F9mtF4Qok6W,iv:/fkk6kWrhlob1Dc0u82umgX5jWm/+S/fdRA1OmlM/mA=,tag:sUGWE09UpStyQ4SlbpWd7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13jkfzky97zmm4n738k3wy8leguhz6xy6xas9r4etnx2esyafadvqat4qve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMDZqUEt2QlAzMTk1ZmJ0
            eGtxR1IzZkhVNDF4WFE0N1RqeVM0c3ZjNlE4CnBxU1NIMkQzbkxNY3c5cE1XQUMw
            ZUVGeTVmUmRWcGJyUFpWV29nYmE1bTgKLS0tIGI1QTZZeDJMVkhCdnZjdFF0YXow
            YjQ0Qmg0QnVHRFJjMHMyZFdzQlUvSG8KOlK6wnqdwhDdaTQL5E/QnyYfxFb0cvfW
            W4C25WUX/JC5qnWYHG6kcDVlmoUBn2Hl/n6wd41jOHvd2kszo0m55g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T13:16:16Z"
    mac: ENC[AES256_GCM,data:Q1iqBmH0D/9sXhjx8/aCwkShuUXnj8EB3TecwHwcvUv6eWgaOab06NRgnsGEkQdM6oI+mhJOMes9/qxiIbCGtM510RhBBz1cM79mksYAxIHf4s0sHpKisLT4J1ZORyRdAdlhbZXf5QnGIwBsVFge6pGvhP3AEyqFr81xcKb++S4=,iv:h5imQZiFszGBvjhb7a34/R0003WT+B2iQJ32c49c4KE=,tag:ow1qk7zdbCcwgQW1guHwwA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.4
