title: madtech labs
email: lab@madtech.cx
description: >- # this means to ignore newlines until "baseurl:"
  madtech homelab configuration, documentation and code
baseurl: "/homelab" # the subpath of your site, e.g. /blog
url: "https://madtech.cx" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: madeddie
github_username:  madeddie

# Build settings
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
