apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akri
  namespace: argocd
spec:
  project: default
  source:
    chart: akri
    repoURL: https://project-akri.github.io/akri/
    targetRevision: 0.13.8
  destination:
    server: "https://kubernetes.default.svc"
    namespace: akri
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
