apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akri
  namespace: argocd
spec:
  project: default
  source:
    chart: akri
    repoURL: https://project-akri.github.io/akri/
    targetRevision: 0.13.8
  destination:
    server: "https://kubernetes.default.svc"
    namespace: akri
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: instances.akri.sh
      jsonPointers:
        - /spec/names/categories
