apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-httpbin
  namespace: argocd
spec:
  project: default
  source:
    path: kustomize
    repoURL: https://github.com/mccutchen/go-httpbin
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: go-httpbin
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
