apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/madeddie/homelab.git
    path: helmcharts/keycloak
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
