apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: keycloak
    targetRevision: 24.5.1
    helm:
      valuesObject:
        ingress:
          enabled: true
          hostname: keycloak.svc.madtech.cx
        proxy: edge
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
