apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    path: deploy
    targetRevision: v0.0.33
    kustomize:
      patches:
        - patch: |-
            kind: ConfigMap
            apiVersion: v1
            metadata:
              name: local-path-config
              namespace: local-path-storage
            data:
              config.json: |-
                {
                        "nodePathMap":[{
                                "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                                "paths":["/var/lib/local-path-provisioner"]
                        }]
                }    
        - patch: |-
            apiVersion: v1
            kind: Namespace
            metadata:
              name: local-path-storage
              labels:
                pod-security.kubernetes.io/enforce: privileged   
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-provisioner
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
