apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  source: metallb
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.9
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
