apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mosquitto
  project: default
  source:
    repoURL: https://github.com/madeddie/homelab.git
    path: helmcharts/mosquitto
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
