apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: sops-secrets-operator
    repoURL: https://isindir.github.io/sops-secrets-operator/
    targetRevision: 0.24.0
    helm:
      valuesObject:
        secretsAsFiles:
        - mountPath: /etc/sops-age-key-file
          name: sops-age-key-file
          secretName: sops-age-key-file
        extraEnv:
        - name: SOPS_AGE_KEY_FILE
          value: /etc/sops-age-key-file/keys.txt
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sops
  syncPolicy:
    automated:
      selfHeal: true
