apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: he-token-secret
    namespace: traefik
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:ccqd3lyiqFsoEEey/vOq,iv:wplQSCR1pm1EcJ68l0tNS3ZcclMlwTZhUh9a991UN+4=,tag:HQkVt76iamqQ54KYPk6X8Q==,type:str]
          stringData:
            hurricane_tokens: ENC[AES256_GCM,data:QQz9aCD6hbhyte6kdTyTLN3DjJxWS3nMoo5y7c4UwW4=,iv:GYX+M/2TJFrjy41mcdiWajJiI8BXlnk9ggx6170VRhE=,tag:sF1ojWNfMNg/BjSZ0EkmlQ==,type:str]
sops:
    age:
        - recipient: age13jkfzky97zmm4n738k3wy8leguhz6xy6xas9r4etnx2esyafadvqat4qve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMDZqUEt2QlAzMTk1ZmJ0
            eGtxR1IzZkhVNDF4WFE0N1RqeVM0c3ZjNlE4CnBxU1NIMkQzbkxNY3c5cE1XQUMw
            ZUVGeTVmUmRWcGJyUFpWV29nYmE1bTgKLS0tIGI1QTZZeDJMVkhCdnZjdFF0YXow
            YjQ0Qmg0QnVHRFJjMHMyZFdzQlUvSG8KOlK6wnqdwhDdaTQL5E/QnyYfxFb0cvfW
            W4C25WUX/JC5qnWYHG6kcDVlmoUBn2Hl/n6wd41jOHvd2kszo0m55g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T13:00:03Z"
    mac: ENC[AES256_GCM,data:C80Zhdwp/O/TlU3xjCmFicw6qgNg6ZF9fiLe4GXipLqZL6ghoxY582NYfa09DJkECZvQmWd9J3o/L1kJrOGGIiYXl+hdv32n7HM5vYT6VJLnDJINRBtixR09hnTwPQ4kxmO7YD2Z81A+zs+edxBCXec4w0WCwaoYwWXs+N/2oT0=,iv:v+8tyd9ZOS047atCSuHAZS2gFNe1YqB475A+lTh2s8M=,tag:mZV8wbY6w3w0aCS6+dvYTw==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
