kind: Service
apiVersion: v1
metadata:
  name: home-madtech
  namespace: traefik
spec:
  type: ExternalName
  ports:
    - name: https
      port: 443
      targetPort: 443
  externalName: home.madtech.cx
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-madtech
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.madtech.cx`) || Host(`assistant.home.madtech.cx`) || Host(`jellyfin.home.madtech.cx`)
      kind: Rule
      services:
        - name: home-madtech
          kind: Service
          port: 443
  tls:
    certResolver: letsencrypt
